<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Logout</name>
   <tag></tag>
   <elementGuidId>bee244c7-c47f-44e3-b7f6-95573a895dbb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='kt_app_sidebar_footer']/div/div[2]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.menu-link</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9699f48b-d792-4bdd-8481-1e020346bbb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menu-link</value>
      <webElementGuid>08eae920-3408-4945-b739-3a9c6bf27b0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Logout</value>
      <webElementGuid>ded0f7eb-7415-4801-aff8-44eca410e0e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_app_sidebar_footer&quot;)/div[@class=&quot;app-sidebar-wrapper&quot;]/div[2]/div[@class=&quot;menu-item&quot;]/div[@class=&quot;menu-link&quot;]</value>
      <webElementGuid>31a35ec3-553a-4d87-9939-bdf943e72fff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kt_app_sidebar_footer']/div/div[2]/div/div</value>
      <webElementGuid>8f87e051-347f-4a21-aa93-d79a3fbaa8c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terms of Use'])[1]/following::div[3]</value>
      <webElementGuid>6bc387a2-8d77-4f1d-981e-b3c6deb0ccc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New Property Request'])[1]/following::div[8]</value>
      <webElementGuid>3a24ccad-326f-4b45-9891-5ad22321557f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[2]/preceding::div[2]</value>
      <webElementGuid>a6c37551-03ac-4657-b2ae-917aaf4e495d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/div</value>
      <webElementGuid>ffd78ed6-133a-4f34-ada4-16d9240bba3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Logout' or . = 'Logout')]</value>
      <webElementGuid>17a0d855-6905-4444-b589-437059e6b1ce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
