<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Copyright  2020-2023. The Next Six Sdn._2664f6</name>
   <tag></tag>
   <elementGuidId>c5127bc2-9d36-495f-9163-97cc3a65ccd9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='kt_app_content_container']/div/div[2]/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.dashboard-profile-image</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>5746e9a9-97f9-492c-9fe5-cfc4463588d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dashboard-profile-image</value>
      <webElementGuid>b578dc52-a08e-45eb-b7d5-126fa9e2092b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://iprofstore.blob.core.windows.net/agents/6041c666aecba1002fd174f7/profile.png?1681891616773</value>
      <webElementGuid>1dc63c68-26e7-4903-a45c-315628c2221a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Profile</value>
      <webElementGuid>90d1bb11-780a-4fc2-bfca-9b07105c38e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_app_content_container&quot;)/div[@class=&quot;dashboard-wrapper&quot;]/div[@class=&quot;dashboard-profile-wrapper&quot;]/div[@class=&quot;dashboard-profile-content&quot;]/img[@class=&quot;dashboard-profile-image&quot;]</value>
      <webElementGuid>7514dfca-2516-420e-8ddf-3206e0987db1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kt_app_content_container']/div/div[2]/div/img</value>
      <webElementGuid>43d64a29-5142-44e0-8fec-dae9530e4fb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Profile']</value>
      <webElementGuid>6f2aeced-50e0-4d2f-9119-cb732b019b33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/img</value>
      <webElementGuid>92019a57-95d9-431f-bb70-fb9eb61af389</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://iprofstore.blob.core.windows.net/agents/6041c666aecba1002fd174f7/profile.png?1681891616773' and @alt = 'Profile']</value>
      <webElementGuid>b1c06b12-db80-4ccd-93d0-405181374ba1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
