<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_ziqhrugmail.com</name>
   <tag></tag>
   <elementGuidId>a26b7930-c061-4762-a989-4ee8f251f922</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='kt_app_content_container']/div/div[2]/div/p[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p.dashboard-profile-email</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>566df53d-5cdb-4d7b-a918-b358ec437cc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dashboard-profile-email</value>
      <webElementGuid>6c5b6f2e-4c7a-4ea9-ae38-7fe9e05c8dff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ziqhru@gmail.com</value>
      <webElementGuid>33b06c3a-1ff2-4573-ade3-244de806ff68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_app_content_container&quot;)/div[@class=&quot;dashboard-wrapper&quot;]/div[@class=&quot;dashboard-profile-wrapper&quot;]/div[@class=&quot;dashboard-profile-content&quot;]/p[@class=&quot;dashboard-profile-email&quot;]</value>
      <webElementGuid>c6232901-f0a8-4512-a983-2b4151f75bef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kt_app_content_container']/div/div[2]/div/p[2]</value>
      <webElementGuid>653d9f04-140d-425c-97f5-143fec85f168</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Approved'])[4]/following::p[2]</value>
      <webElementGuid>0438d295-533f-4db8-b5cc-9db8db7016d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit profile'])[1]/preceding::p[2]</value>
      <webElementGuid>637a8459-3405-4d78-9890-3d169c457b6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Invite a Friend'])[1]/preceding::p[2]</value>
      <webElementGuid>dcf580b0-1af8-4637-9046-92efb4eb3798</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ziqhru@gmail.com']/parent::*</value>
      <webElementGuid>7efa59ab-6748-4f5b-8717-170dc1694b08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/p[2]</value>
      <webElementGuid>28e43e22-753a-4ad4-8398-e775215c36fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'ziqhru@gmail.com' or . = 'ziqhru@gmail.com')]</value>
      <webElementGuid>e0db13fa-9d18-4bfd-98e4-91c29f7d0ce7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
