<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>email_timestamp</name>
   <tag></tag>
   <elementGuidId>611a80e7-1c23-43a8-96fd-6378c3556101</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;AQAAABrsNKsBAAAAjEZ/cwAAAAA=&quot;]/div/div/div[2]/div[2]/div[2]/span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
