<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>resetpasswordlink</name>
   <tag></tag>
   <elementGuidId>55d3db29-2431-4940-9c66-bb61ab7abd70</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;ReadingPaneContainerId&quot;]/div/div/div/div/div/div[3]/div[1]/div/div/div/div/div[3]/div/div/div/b[2]/</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
