<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Register here</name>
   <tag></tag>
   <elementGuidId>03a73197-8105-4bd3-9034-72b64d75f38a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='kt_login_signin_form']/div[6]/div/span/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.auth-register-here</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>861612b5-4244-44e1-8836-9fd4fa813797</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://sit.nextsix.com/signup</value>
      <webElementGuid>9173e0d6-acdd-4b83-92e8-59f1731300d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>auth-register-here</value>
      <webElementGuid>0278c829-a655-4d54-88cb-99362cc50081</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>9ab69a15-a13d-4410-b456-b3320fe90b2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>noopener noreferrer</value>
      <webElementGuid>cfaae009-7ebd-4bcc-9328-ab866642c4b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Register here</value>
      <webElementGuid>7bfed72e-953c-4ca6-8e5b-c96d3de39d8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_login_signin_form&quot;)/div[@class=&quot;d-flex flex-center flex-column-auto&quot;]/div[@class=&quot;d-flex align-items-center auth-account-yet&quot;]/span[1]/a[@class=&quot;auth-register-here&quot;]</value>
      <webElementGuid>42102dde-4dac-4179-bcd2-4a750ed80f3f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='kt_login_signin_form']/div[6]/div/span/a</value>
      <webElementGuid>b33db56c-cbdd-431a-ae72-b4cf02a0b819</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Register here')]</value>
      <webElementGuid>65e50c7b-3f54-49b6-8b92-11fa9d1ef031</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign In'])[1]/following::a[1]</value>
      <webElementGuid>cac86228-2922-4fe0-858a-6bc1a2845c56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://sit.nextsix.com/signup')]</value>
      <webElementGuid>799e0f60-9732-4d89-be52-818b6a4436ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>ccc750b6-e3d4-4faf-aca2-5e32d06d1f3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://sit.nextsix.com/signup' and (text() = ' Register here' or . = ' Register here')]</value>
      <webElementGuid>9e1e4406-d10c-4ec6-8348-16f94394ef69</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
