<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_User Name  Email Address_username</name>
   <tag></tag>
   <elementGuidId>c3e8ae99-d8c7-41d0-9ea4-d8ba042f9e71</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='username']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;kt_login_signin_form&quot;)/div[@class=&quot;fv-row mb-8&quot;]/div[@class=&quot;auth-input-box&quot;]/input[@class=&quot;form-control bg-transparent auth-input-field&quot;][count(. | //input[@class = 'form-control bg-transparent auth-input-field']) = count(//input[@class = 'form-control bg-transparent auth-input-field'])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;username&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f47a4b40-d34f-4143-9aac-0ae356950ef1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>user name / email address</value>
      <webElementGuid>ff512872-9494-45aa-b299-de9093dc2c03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>username</value>
      <webElementGuid>a354b421-9e9c-4625-af12-2f08a18d76f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control bg-transparent auth-input-field</value>
      <webElementGuid>8961a87e-f993-4fcd-8ab0-f0fb8bfe0710</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>username</value>
      <webElementGuid>dc02e805-7271-4d62-bc03-376bc6300e1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>42cb3969-5149-46c9-afbe-a0ea2ddea4a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_login_signin_form&quot;)/div[@class=&quot;fv-row mb-8&quot;]/div[@class=&quot;auth-input-box&quot;]/input[@class=&quot;form-control bg-transparent auth-input-field&quot;]</value>
      <webElementGuid>b2898162-ec4d-425f-a2c2-dd1571c6e738</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='username']</value>
      <webElementGuid>ac5944f0-6243-47b0-891e-452c82689df0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='kt_login_signin_form']/div[2]/div/input</value>
      <webElementGuid>4a4ce1de-c413-4d01-862d-8c2b3d102384</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>e7a017d9-2843-45f2-946b-acf221748c71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'user name / email address' and @name = 'username' and @type = 'username']</value>
      <webElementGuid>1697fa1c-46b9-4d14-bb82-b436e978a37b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
