<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_User Name  Email Address</name>
   <tag></tag>
   <elementGuidId>5e4e3661-9e59-46ba-bf22-ceedf8aaf63a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='kt_login_signin_form']/div[2]/div/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>label.form-label.auth-input-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>209eb94c-e6f7-4ed9-876a-ce3664e6e154</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-label auth-input-text</value>
      <webElementGuid>c0a1602c-c9d5-4a09-968b-2ef892ebb2aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>User Name / Email Address</value>
      <webElementGuid>99fa3826-ba39-4890-bde7-b148b482e927</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_login_signin_form&quot;)/div[@class=&quot;fv-row mb-8&quot;]/div[@class=&quot;auth-input-box&quot;]/label[@class=&quot;form-label auth-input-text&quot;]</value>
      <webElementGuid>8f20ced4-40e9-46e2-8301-156f06921a27</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='kt_login_signin_form']/div[2]/div/label</value>
      <webElementGuid>d8ff8eb6-600a-4ce3-93da-d2cbc9d293a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/preceding::label[1]</value>
      <webElementGuid>83988499-269c-465a-b3ff-d77fbb325ad9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='forgot password'])[1]/preceding::label[2]</value>
      <webElementGuid>b0293aa7-1a73-4b89-8662-2bc22be3a020</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='User Name / Email Address']/parent::*</value>
      <webElementGuid>d1b6edb4-a314-4201-87e3-c1d0fe673f12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label</value>
      <webElementGuid>6befaa82-c92e-400d-942d-e5b150ee92b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'User Name / Email Address' or . = 'User Name / Email Address')]</value>
      <webElementGuid>377199c4-cb70-4d90-8a41-8f1275db8cd7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
