<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_ziqhrugmail.com</name>
   <tag></tag>
   <elementGuidId>5c4de099-f7b5-4648-a3b6-aef4bc6cf5e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='kt_app_content_container']/div/div[2]/div/p[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p.dashboard-profile-email</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>aefc94f0-f928-4cb1-8ad3-64f348ed0532</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dashboard-profile-email</value>
      <webElementGuid>0d964093-6719-4f96-b5ad-583eb8b3bbbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ziqhru@gmail.com</value>
      <webElementGuid>85da97b3-7d88-4302-acf2-7827bc4629c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_app_content_container&quot;)/div[@class=&quot;dashboard-wrapper&quot;]/div[@class=&quot;dashboard-profile-wrapper&quot;]/div[@class=&quot;dashboard-profile-content&quot;]/p[@class=&quot;dashboard-profile-email&quot;]</value>
      <webElementGuid>db24e9cf-42df-48e4-a2d6-9c2ce7926dae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kt_app_content_container']/div/div[2]/div/p[2]</value>
      <webElementGuid>a5a8c5f3-e16d-44b1-bd3f-4c88d3ca4698</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Approved'])[7]/following::p[2]</value>
      <webElementGuid>adf38737-71e3-492c-b3e2-cfecb6a4cf94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit profile'])[1]/preceding::p[2]</value>
      <webElementGuid>e9fd3859-ca56-4613-9863-b6d6aa339525</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Activity Logs'])[1]/preceding::p[2]</value>
      <webElementGuid>5ac0c22c-7faa-4f9a-9ba7-cb91bf601e28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ziqhru@gmail.com']/parent::*</value>
      <webElementGuid>cab41613-bd97-473b-a735-981ffca30277</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/p[2]</value>
      <webElementGuid>7c923ace-6ef4-440f-b123-a4db40953d58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'ziqhru@gmail.com' or . = 'ziqhru@gmail.com')]</value>
      <webElementGuid>ecebd4d7-77e6-40e9-b6b1-35786d73c43d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
