<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Ziqh</name>
   <tag></tag>
   <elementGuidId>26f0b73f-b1dc-4030-b76a-f92b312a8cef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='kt_app_content_container']/div/div[2]/div/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p.dashboard-profile-name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>05df6f17-fee7-4cdc-a615-0230977b040c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dashboard-profile-name</value>
      <webElementGuid>3ff042b5-fb3b-4f29-b3c0-ad3136060e9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ziqh</value>
      <webElementGuid>bfd83a7a-d9de-42bf-ab85-2e7677770238</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_app_content_container&quot;)/div[@class=&quot;dashboard-wrapper&quot;]/div[@class=&quot;dashboard-profile-wrapper&quot;]/div[@class=&quot;dashboard-profile-content&quot;]/p[@class=&quot;dashboard-profile-name&quot;]</value>
      <webElementGuid>58b1dbd7-8ff2-4f57-ac98-07ee320eb5e1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kt_app_content_container']/div/div[2]/div/p</value>
      <webElementGuid>97bdde57-d8d4-41ea-86e9-e457a4b23dd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Approved'])[7]/following::p[1]</value>
      <webElementGuid>9e54f705-7632-4748-8def-ef2f4b9d5de4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit profile'])[1]/preceding::p[3]</value>
      <webElementGuid>9a38ca33-bac6-4237-9d0c-6eb1730a2ff3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Activity Logs'])[1]/preceding::p[3]</value>
      <webElementGuid>06531966-8e17-476d-a81c-47ecbdba48de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ziqh']/parent::*</value>
      <webElementGuid>a22c849d-5833-4bad-9168-f87e40700daa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/p</value>
      <webElementGuid>2493fa5b-9ce0-4095-9152-f25cef49608f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Ziqh' or . = 'Ziqh')]</value>
      <webElementGuid>ed0b601d-b673-4ca8-8796-ce350bf81bdd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
