<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Agent Login</name>
   <tag></tag>
   <elementGuidId>578ec451-fe04-4fc2-8f83-1f58cd5d6d61</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//nav[@id='header']/div/div[2]/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.btn-sign-in2.btn.btn-secondary</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>84b11f44-e696-4a65-9e96-49278003d31d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://sit-agent.nextsix.com</value>
      <webElementGuid>0f0c6ef2-2bd7-411e-95f7-7a45c2558f2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>ec7bb6c3-608c-4e01-b70e-7d4aac1aef3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-sign-in2 btn btn-secondary</value>
      <webElementGuid>b8cccc12-f9e1-469d-8f74-feb22799dbbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Agent Login</value>
      <webElementGuid>66f66e6c-adff-4860-9042-2e67cbd049e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header&quot;)/div[@class=&quot;header-content2 container&quot;]/div[@class=&quot;header-right2&quot;]/div[@class=&quot;btn-desktop-view&quot;]/a[@class=&quot;btn-sign-in2 btn btn-secondary&quot;]</value>
      <webElementGuid>6c0e109d-8487-4621-8cc0-783f61cddee2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='header']/div/div[2]/div/a</value>
      <webElementGuid>ad46a8a7-bd4f-4ca7-9fd1-5b5925081bed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Agent Login')]</value>
      <webElementGuid>cf08501b-d13f-4aca-84f6-090cf8b50072</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Agent Sign Up'])[1]/preceding::a[1]</value>
      <webElementGuid>8e38d022-99ff-4900-a526-6a2bc1cfaf28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Agent Login']/parent::*</value>
      <webElementGuid>901b5f1d-a021-4840-a57a-b83ddb158f4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://sit-agent.nextsix.com')]</value>
      <webElementGuid>1364cd30-4b1d-47da-adc0-dcae528fb957</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a</value>
      <webElementGuid>e8ac6abb-da01-4965-a879-1c6005da1406</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://sit-agent.nextsix.com' and (text() = 'Agent Login' or . = 'Agent Login')]</value>
      <webElementGuid>434c2966-b5bb-4795-ad0e-b24e456badbd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
