<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Lucky Draw</name>
   <tag></tag>
   <elementGuidId>55298dd7-d2d0-49cb-bea1-a39f888eac37</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[8]/div/div/div[2]/div[4]/ul/li/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.footer-top-event2.col-12.col-sm-6.col-lg-2 > ul.footer-title-list2 > li.footer-title-listItem2 > a.footer-title-listItemLink2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6df689c0-b87c-43cf-94b1-85d6c5d4fc82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>footer-title-listItemLink2</value>
      <webElementGuid>01433a0d-c412-49ba-a37e-6edc13f21c2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/luckydraw</value>
      <webElementGuid>4b600614-a467-4d55-b70f-8c7828dc276f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lucky Draw</value>
      <webElementGuid>06c9a716-c7ff-43e8-8384-eda722ac0fb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;footer-top-wrapper2&quot;]/div[@class=&quot;footer-top-content container&quot;]/div[@class=&quot;footer-top-inner2&quot;]/div[@class=&quot;footer-top-innerRight2&quot;]/div[@class=&quot;footer-top-event2 col-12 col-sm-6 col-lg-2&quot;]/ul[@class=&quot;footer-title-list2&quot;]/li[@class=&quot;footer-title-listItem2&quot;]/a[@class=&quot;footer-title-listItemLink2&quot;]</value>
      <webElementGuid>a5cc36ac-2ccb-4db7-b810-26206c6a74d0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[8]/div/div/div[2]/div[4]/ul/li/a</value>
      <webElementGuid>00cf4c46-9361-4c4a-887c-809dd83fa8b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Lucky Draw')])[2]</value>
      <webElementGuid>a12e8737-508b-4436-80bc-6946d4b9eb85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Events'])[1]/following::a[1]</value>
      <webElementGuid>40de00c1-7e0e-4bb4-93b9-4a3f8f2622da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lucky Draw T&amp;C'])[1]/following::a[1]</value>
      <webElementGuid>eaafc9da-bce6-46d6-842c-d11b61b40365</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Popular Search'])[1]/preceding::a[1]</value>
      <webElementGuid>5461fdea-12b3-4abc-9f84-d55a8d970824</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Popular Locations'])[1]/preceding::a[1]</value>
      <webElementGuid>7ddc491d-13a1-4894-b187-71f45240dd88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Lucky Draw']/parent::*</value>
      <webElementGuid>88c12db5-ddf6-4f79-9eb2-00a8e55ac6c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/luckydraw')])[2]</value>
      <webElementGuid>91a27218-21f6-4163-8904-807ccce536e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/ul/li/a</value>
      <webElementGuid>f3976b54-bab5-470a-acda-22f9e9534b71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/luckydraw' and (text() = 'Lucky Draw' or . = 'Lucky Draw')]</value>
      <webElementGuid>4db2fce9-24e1-44ac-b718-21bfe1bfecdd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
