<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Ren ID</name>
   <tag></tag>
   <elementGuidId>ef57ffa9-5025-49f4-916a-0352911b181c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='kt_app_content_container']/div/div/div[2]/div/div/div/div[2]/div[4]/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.col.profile-text-medium</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a3c871a5-4bd9-49e0-b53f-834e905b0d13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col profile-text-medium</value>
      <webElementGuid>6b281aac-40d6-4b2e-bc0d-5b98ecc8392d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ren ID</value>
      <webElementGuid>25eea936-7eff-498a-85f4-67ef8a14d968</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_app_content_container&quot;)/div[@class=&quot;page-wrapper&quot;]/div[@class=&quot;page-statistic-wrapper&quot;]/div[@class=&quot;profile-wrapper-upper&quot;]/div[@class=&quot;row justify-content-center&quot;]/div[@class=&quot;profile-wrapper-subheader&quot;]/div[@class=&quot;row column-gap-4&quot;]/div[@class=&quot;col d-flex flex-column justify-content-between row-gap-3 row-gap-sm-0&quot;]/div[@class=&quot;row align-items-center&quot;]/div[@class=&quot;col order-3 order-sm-0 mx-3 ms-sm-3 profile-display-box&quot;]/div[@class=&quot;row align-items-center&quot;]/div[@class=&quot;col profile-text-medium&quot;]</value>
      <webElementGuid>bf1584f7-148c-4cb2-96a1-7960624937cc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kt_app_content_container']/div/div/div[2]/div/div/div/div[2]/div[4]/div/div/div</value>
      <webElementGuid>5a6be141-eabb-4016-8cde-dfb44b529ab9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Title Specialist'])[1]/following::div[4]</value>
      <webElementGuid>b347ab4d-c241-486d-b511-b914d6ce8183</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Area Specialist'])[1]/following::div[5]</value>
      <webElementGuid>9c678b40-9e62-4392-a0e0-453ef12c8b7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Resubmit'])[1]/preceding::div[1]</value>
      <webElementGuid>3541b7d2-71c0-4df3-a854-4d12891ae662</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div</value>
      <webElementGuid>cacd9b01-7aa1-4f70-9095-aa52500cfb5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Ren ID' or . = 'Ren ID')]</value>
      <webElementGuid>197bb2f7-a8a4-4631-9092-b7c7cc7f8e58</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
