<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Stateoption Wilayah Persekutuan Kuala L_c4ce0c</name>
   <tag></tag>
   <elementGuidId>2196ba37-c6fb-4a7e-abe4-19ee49e4bc07</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='kt_app_content_container']/div/div/div[3]/div[2]/div[8]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>77566fce-a6cb-4c47-af22-befdc4706a18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row align-items-center profile-input-box </value>
      <webElementGuid>70cf7709-8b0f-40c1-8729-e6fecfa49ca1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Stateoption Wilayah Persekutuan Kuala Lumpur focused, 1 of 16. 16 results available. Use Up and Down to choose options, press Enter to select the currently focused option, press Escape to exit the menu, press Tab to select the option and exit the menu.Wilayah Persekutuan Kuala LumpurWilayah Persekutuan Kuala LumpurJohorKedahKelantanMelakaNegeri SembilanPahangPenangPerakPerlisSabahSarawakSelangorTerengganuWilayah Persekutuan LabuanWilayah Persekutuan Putrajaya</value>
      <webElementGuid>0152bae6-2019-4efa-bbb5-bf9321742a3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_app_content_container&quot;)/div[@class=&quot;page-wrapper&quot;]/div[@class=&quot;page-statistic-wrapper&quot;]/div[@class=&quot;profile-wrapper-lower&quot;]/div[@class=&quot;profile-wrapper-container&quot;]/div[@class=&quot;row justify-content-between profile-mx-inherit&quot;]/div[@class=&quot;col-12 profile-col-md&quot;]/div[@class=&quot;row align-items-center profile-input-box&quot;]</value>
      <webElementGuid>da61d659-5280-4819-a97d-13f4456096ff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kt_app_content_container']/div/div/div[3]/div[2]/div[8]/div/div</value>
      <webElementGuid>1873de8b-681e-4d6a-b7a2-c8a9abc6245d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Address'])[1]/following::div[3]</value>
      <webElementGuid>5eb55a63-00dd-4b32-ae90-39784d0f7549</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Phone Number'])[1]/following::div[7]</value>
      <webElementGuid>d6cf7bc9-0762-4289-8b98-d27c1be2450f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div</value>
      <webElementGuid>bcca852d-b1a6-4135-b49c-069e13831084</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Stateoption Wilayah Persekutuan Kuala Lumpur focused, 1 of 16. 16 results available. Use Up and Down to choose options, press Enter to select the currently focused option, press Escape to exit the menu, press Tab to select the option and exit the menu.Wilayah Persekutuan Kuala LumpurWilayah Persekutuan Kuala LumpurJohorKedahKelantanMelakaNegeri SembilanPahangPenangPerakPerlisSabahSarawakSelangorTerengganuWilayah Persekutuan LabuanWilayah Persekutuan Putrajaya' or . = 'Stateoption Wilayah Persekutuan Kuala Lumpur focused, 1 of 16. 16 results available. Use Up and Down to choose options, press Enter to select the currently focused option, press Escape to exit the menu, press Tab to select the option and exit the menu.Wilayah Persekutuan Kuala LumpurWilayah Persekutuan Kuala LumpurJohorKedahKelantanMelakaNegeri SembilanPahangPenangPerakPerlisSabahSarawakSelangorTerengganuWilayah Persekutuan LabuanWilayah Persekutuan Putrajaya')]</value>
      <webElementGuid>1276b420-2150-4a16-8d98-e28bb22e1169</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
