<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Pro PackPackageThe Roof RealtyCompany N_99e432</name>
   <tag></tag>
   <elementGuidId>d658eaeb-06ee-458d-a5e8-a37c680790e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='kt_app_content_container']/div/div/div[2]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.profile-wrapper-subheader</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2ddbcb9a-70c7-4f22-93f8-c889a734df2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>profile-wrapper-subheader</value>
      <webElementGuid>53743c88-31e8-4bd0-bea3-5084307364f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pro PackPackageThe Roof RealtyCompany NameHQBranchSelangorSpecialized StateSubang JayaSpecialized AreaArea SpecialistAlam ImpianTitle SpecialistThe Condo, The ApartmentRen IDResubmitPersonal InformationsE-Business Card</value>
      <webElementGuid>d4388389-d82c-4681-85b7-68a2a70007ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_app_content_container&quot;)/div[@class=&quot;page-wrapper&quot;]/div[@class=&quot;page-statistic-wrapper&quot;]/div[@class=&quot;profile-wrapper-upper&quot;]/div[@class=&quot;row justify-content-center&quot;]/div[@class=&quot;profile-wrapper-subheader&quot;]</value>
      <webElementGuid>238334c9-d19a-4a2d-9ffd-390a1d95ef68</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kt_app_content_container']/div/div/div[2]/div/div</value>
      <webElementGuid>1dfd32f4-9285-4237-8ca5-f5f4ecc1b40e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='...........'])[1]/following::div[3]</value>
      <webElementGuid>78bc2622-0c86-4d8b-97b0-37dda02b7cd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Profile'])[2]/following::div[5]</value>
      <webElementGuid>258704a7-b474-4518-94bf-4d34c6201512</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div[2]/div/div</value>
      <webElementGuid>2196a3bf-e987-4a21-823f-c3b1440542f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Pro PackPackageThe Roof RealtyCompany NameHQBranchSelangorSpecialized StateSubang JayaSpecialized AreaArea SpecialistAlam ImpianTitle SpecialistThe Condo, The ApartmentRen IDResubmitPersonal InformationsE-Business Card' or . = 'Pro PackPackageThe Roof RealtyCompany NameHQBranchSelangorSpecialized StateSubang JayaSpecialized AreaArea SpecialistAlam ImpianTitle SpecialistThe Condo, The ApartmentRen IDResubmitPersonal InformationsE-Business Card')]</value>
      <webElementGuid>6f299348-2568-4fb3-a5f0-0e34c36bc812</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
