<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Male</name>
   <tag></tag>
   <elementGuidId>c11df2f3-92d4-4744-9e39-c5dea62e562a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='kt_app_content_container']/div/div/div[3]/div[2]/div[4]/div[2]/div/div/div/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.selectInput__single-value.css-134s3gk-singleValue</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = '${gender}' or . = '${gender}')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4b0d3618-e951-4135-ae2b-a2cfa4f3b2dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectInput__single-value css-134s3gk-singleValue</value>
      <webElementGuid>3894cdc0-521b-47af-b552-d59628a91cb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>${gender}</value>
      <webElementGuid>9b8b82bf-76e9-4732-a080-139a185f9f15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_app_content_container&quot;)/div[@class=&quot;page-wrapper&quot;]/div[@class=&quot;page-statistic-wrapper&quot;]/div[@class=&quot;profile-wrapper-lower&quot;]/div[@class=&quot;profile-wrapper-container&quot;]/div[@class=&quot;row justify-content-between profile-mx-inherit&quot;]/div[@class=&quot;col-12 profile-col-md&quot;]/div[@class=&quot;row align-items-center profile-input-box&quot;]/div[@class=&quot;col&quot;]/div[@class=&quot;css-1mw99yp-container&quot;]/div[@class=&quot;selectInput__control selectInput__control--is-focused selectInput__control--menu-is-open css-1av5qop-control&quot;]/div[@class=&quot;selectInput__value-container selectInput__value-container--has-value css-1ugjhs6&quot;]/div[@class=&quot;selectInput__single-value css-134s3gk-singleValue&quot;]</value>
      <webElementGuid>9ce8f3d8-aec6-41b6-a703-063bafdf2d11</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kt_app_content_container']/div/div/div[3]/div[2]/div[4]/div[2]/div/div/div/div/div/div</value>
      <webElementGuid>e596f5f2-0767-48db-8417-b4b43438c862</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gender'])[1]/following::div[4]</value>
      <webElementGuid>ea088fa5-c0c8-4e63-a013-b597c048ec5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nick Name'])[1]/following::div[7]</value>
      <webElementGuid>bcc62e76-d7a6-4a24-a3d0-fdc5ff39e9a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Male'])[2]/preceding::div[4]</value>
      <webElementGuid>e03c3ca3-6c72-44ab-a6c2-2318cf4cb53d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Female'])[1]/preceding::div[5]</value>
      <webElementGuid>a5c11509-69cf-476c-a52a-a9faa1cb4b21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Male']/parent::*</value>
      <webElementGuid>5d8e2bfd-29f3-4df0-a831-51b1f87829fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/div/div/div/div/div</value>
      <webElementGuid>e8444961-edb4-46c4-adf5-e3c8723a8a68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Male' or . = 'Male')]</value>
      <webElementGuid>cd5b6705-106d-40a3-bbf3-5debe6e19c80</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
