<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Full Name_Full Name</name>
   <tag></tag>
   <elementGuidId>99904f58-4533-41b9-a47d-4055df4d28cd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@value = 'Ziqh']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>
</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d0096c10-7730-40a8-aaf9-32302829785a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1b1291d9-edd7-46c6-b99b-a5426f988049</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Full Name</value>
      <webElementGuid>c762b39b-fb57-4031-a69a-b6cfb9d3c27c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Full Name</value>
      <webElementGuid>bba27296-95a8-436c-8236-1f1ecad67152</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Full Name</value>
      <webElementGuid>1e069328-e519-4b5d-8fb5-4f4048d413d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control profile-input-trans profile-input-value profile-input-disabled profile-input-placeholder px-0</value>
      <webElementGuid>f900b880-39d4-4478-8b66-96d8162fbfac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Ziqh</value>
      <webElementGuid>01239c7b-f37f-4361-aefb-f675f851141b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Full Name&quot;)</value>
      <webElementGuid>ba08fe92-9b59-42e8-9232-b9d002efcec1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Full Name']</value>
      <webElementGuid>05a11094-2047-4ce3-ab0c-22e5a4366bba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kt_app_content_container']/div/div/div[3]/div[2]/div[2]/div/div/div/input</value>
      <webElementGuid>b8f215a5-62c5-4a10-a8aa-f29e7c2ad6c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>d3e8ea85-634d-4bcd-aef8-ac8d45f93ac1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'Full Name' and @id = 'Full Name' and @placeholder = 'Full Name']</value>
      <webElementGuid>203aac9c-8dc2-4aa0-90c2-24a4e7649baa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
