<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Ren ID_renId_1</name>
   <tag></tag>
   <elementGuidId>83a60ce6-325e-4a9e-8344-70bd0cecf4a1</elementGuidId>
   <imagePath>Screenshots/Targets/Page_The Next Six Agent (SIT)/input_Ren ID_renId.png</imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='renId']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#renId</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value>Screenshots/Targets/Page_The Next Six Agent (SIT)/input_Ren ID_renId.png</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@value = '${renid}']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c76e81fc-d3b3-47c0-b0ae-f24c100e54f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8e038b4c-9447-479a-834e-e1d0dba3aa01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>renId</value>
      <webElementGuid>f1c3e862-5f3a-44fb-93ef-3c806fe5d04a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-0 w-100 profile-input-text profile-text-medium fs-6</value>
      <webElementGuid>0d62c885-d67a-4762-8de4-69b56737d594</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>${renid}</value>
      <webElementGuid>71b97c34-2150-40dd-beae-0a31b6ebc629</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;renId&quot;)</value>
      <webElementGuid>f2a23e19-a12f-470b-a95d-741801e16fa8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='renId']</value>
      <webElementGuid>58d0d9d7-b2ca-4080-aa90-69e16c7b069c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kt_app_content_container']/div/div/div[2]/div/div/div/div[2]/div[4]/div/div/div/input</value>
      <webElementGuid>1d684486-6177-447c-af1e-84cd516dfecc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>10654ba7-290b-4c4a-833e-617b7af5fe7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'renId']</value>
      <webElementGuid>98ecbd46-1052-443d-92ab-d778d3dc063b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
