<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>package</name>
   <tag></tag>
   <elementGuidId>715f0f28-287f-48d2-a15f-d86a97e6b0da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;kt_app_content_container&quot;]/div[1]/div/div[2]/div/div/div[1]/div[2]/div[1]/div[1]/text()</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
