<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Negeri Sembilan</name>
   <tag></tag>
   <elementGuidId>123d6193-34d5-40cd-9f08-a289bc22ff04</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react-select-13-option-5']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Negeri Sembilan' or . = 'Negeri Sembilan')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#react-select-13-option-5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a8decd28-09bf-4637-b00e-ccb0ea36efe7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>propmaster-select__option propmaster-select__option--is-focused css-1oayvia-option</value>
      <webElementGuid>4f0c2f80-0e0c-45f8-ad99-12b0c81ce1e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>926381f0-dab2-4ea4-8b85-f7d5c6461ed2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-select-13-option-5</value>
      <webElementGuid>c5dc1aef-f326-4099-b6f8-a74cbf708fe8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>c6a15090-cb8c-436a-b138-f6bb96c63f61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Negeri Sembilan</value>
      <webElementGuid>f628ed10-942f-4802-9a1a-a0bb9c8376cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-select-13-option-5&quot;)</value>
      <webElementGuid>973d25b7-b327-41d2-a38a-e0e4133fb3dd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='react-select-13-option-5']</value>
      <webElementGuid>720f8eb2-b664-443d-8c8b-67cf8ac4bf5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react-select-13-listbox']/div/div[6]</value>
      <webElementGuid>72be3164-1258-4398-abf6-0f192d4b9dd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Melaka'])[1]/following::div[1]</value>
      <webElementGuid>72953545-69a7-4786-bc0a-66a4024af98c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kelantan'])[1]/following::div[2]</value>
      <webElementGuid>37e33184-1c11-4caa-9089-cf9b77b56548</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pahang'])[1]/preceding::div[1]</value>
      <webElementGuid>07cbca96-e189-4823-8afc-07e50deb5547</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Penang'])[1]/preceding::div[2]</value>
      <webElementGuid>c7b9abb3-0155-473f-86ff-e0bb28b632d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Negeri Sembilan']/parent::*</value>
      <webElementGuid>fdb746c4-1e05-41b5-b1f9-824a3435ef72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[6]</value>
      <webElementGuid>8aaa68d9-a3d7-4b9b-908b-b4f64d920be3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'react-select-13-option-5' and (text() = 'Negeri Sembilan' or . = 'Negeri Sembilan')]</value>
      <webElementGuid>a642faf9-1e20-4b46-afd5-bde2db390ff9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
