<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Select Property Type</name>
   <tag></tag>
   <elementGuidId>d92addbc-dbe7-43c6-b266-0efe4ecf2a74</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react-select-10-placeholder']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Select Property Type' or . = 'Select Property Type')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#react-select-10-placeholder</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c42c549a-91d5-48ad-962d-cd4d00d9342f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>propmaster-select__placeholder css-1bkpx9o-placeholder</value>
      <webElementGuid>14d372be-840f-466e-a1b3-4f3941500701</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-select-10-placeholder</value>
      <webElementGuid>0e0bfe96-4f09-45e0-a77a-c1552f670814</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select Property Type</value>
      <webElementGuid>85a16f7a-c7e2-4bf7-950e-95f80f5fe1b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-select-10-placeholder&quot;)</value>
      <webElementGuid>5e0096ba-e6d0-44bd-b774-31d43f6c10fa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='react-select-10-placeholder']</value>
      <webElementGuid>c26a494e-9d57-4bf4-9950-9f834d9e662c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='propType']/div/div/div</value>
      <webElementGuid>5e607d77-46fc-4f8b-bb47-9d0f07d43c02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Property Type *'])[1]/following::div[4]</value>
      <webElementGuid>e6d1f86b-539e-45c7-924c-ed782bdacff6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apartment/Flat'])[1]/following::div[9]</value>
      <webElementGuid>e6670fa2-d2ba-4f50-b314-61c830e506d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apartment'])[1]/preceding::div[4]</value>
      <webElementGuid>224334c9-7d2b-4e78-a536-63184858d8d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Flat'])[1]/preceding::div[5]</value>
      <webElementGuid>a5a9cc59-41cd-4711-b155-894700f15307</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Select Property Type']/parent::*</value>
      <webElementGuid>466ba77f-3bd7-47e3-bf62-1c6bfd9a8d6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[3]/div/div/div/div/div</value>
      <webElementGuid>6ad4f3e8-2412-496a-8cd3-9ff988755a41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'react-select-10-placeholder' and (text() = 'Select Property Type' or . = 'Select Property Type')]</value>
      <webElementGuid>99b660eb-7673-4aed-aa9f-39042f288052</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
