<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_ApartmentFlat</name>
   <tag></tag>
   <elementGuidId>644a7956-4b1f-444e-afc5-50388e292fec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react-select-9-option-0']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Apartment/Flat' or . = 'Apartment/Flat')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#react-select-9-option-0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5cc078be-d9f8-4c76-8922-e824d8158fe3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>propmaster-select__option propmaster-select__option--is-focused css-1oayvia-option</value>
      <webElementGuid>e0bbfdad-9351-463f-8049-d8f874f6322b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1bc236a5-5872-4b8b-b601-73dbd758240b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-select-9-option-0</value>
      <webElementGuid>652a81b7-fcc6-421e-a0e5-f0d37a3a3795</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>b1dc9325-18a7-4533-bcd6-553a2818d723</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Apartment/Flat</value>
      <webElementGuid>dd772231-42c2-4770-8d4e-707cce8bfcac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-select-9-option-0&quot;)</value>
      <webElementGuid>eb5c02e7-ab12-45a8-85c6-949a97e87419</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='react-select-9-option-0']</value>
      <webElementGuid>63bf5d27-dfbf-4386-b241-ce77e9e320eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react-select-9-listbox']/div/div</value>
      <webElementGuid>a05882ec-79ca-43fd-91e4-cc7ea5459ac5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Property Category'])[1]/following::div[7]</value>
      <webElementGuid>f726f1bc-12f1-4e1e-9761-2828a4eac635</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Property Category *'])[1]/following::div[11]</value>
      <webElementGuid>65191a40-d47e-481f-8f74-b6731f463be4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Condo/Serviced Residence'])[1]/preceding::div[1]</value>
      <webElementGuid>0ecb1b8c-e58e-46cc-ab92-3a6950c0d00b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Property Type *'])[1]/preceding::div[2]</value>
      <webElementGuid>00847194-c122-404b-9111-f032ed766b57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Apartment/Flat']/parent::*</value>
      <webElementGuid>5c20d163-bdee-4d6e-a4ea-47415bf97cb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div/div/div</value>
      <webElementGuid>e313aad4-76cd-4644-b746-92e22b82de20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'react-select-9-option-0' and (text() = 'Apartment/Flat' or . = 'Apartment/Flat')]</value>
      <webElementGuid>c9f93d47-a96e-4b46-b75c-dca022dd3f8c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
