<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Labu</name>
   <tag></tag>
   <elementGuidId>adbeb055-75d1-4ea6-8c93-584bd4503a28</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react-select-14-option-18']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Labu' or . = 'Labu')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#react-select-14-option-18</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a77d35e1-2a67-43c7-b079-101d2a4b6210</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>propmaster-select__option propmaster-select__option--is-focused css-1oayvia-option</value>
      <webElementGuid>f9fc7659-1d97-44f3-988c-35a71b1a34d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>0e36bc5b-e1f8-4adc-97d8-fa607363c928</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-select-14-option-18</value>
      <webElementGuid>662b3a73-440d-4477-bede-0f1d429699bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>60628ce3-8bcb-4bec-b606-3e4de23a97a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Labu</value>
      <webElementGuid>92768067-2c5e-4b59-9def-cf9695c3d940</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-select-14-option-18&quot;)</value>
      <webElementGuid>338b54d5-6121-4fc9-b09a-d4a3fc03f8eb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='react-select-14-option-18']</value>
      <webElementGuid>789818d3-53e1-4d46-b276-7678149ee728</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react-select-14-listbox']/div/div[19]</value>
      <webElementGuid>b316a905-8aa2-4194-8d09-2eea02714609</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kuala Pilah'])[1]/following::div[1]</value>
      <webElementGuid>12290e77-2baa-4ad6-8e10-f6ed52acbbce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kuala Klawang'])[1]/following::div[2]</value>
      <webElementGuid>7ad1ed8a-f94f-42b1-970e-bf56e3951611</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lenggeng'])[1]/preceding::div[1]</value>
      <webElementGuid>8412632d-fdee-453e-8bea-47c1f2a46bdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Linggi'])[1]/preceding::div[2]</value>
      <webElementGuid>ea676458-e220-4b56-93a8-87dc8974d76e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Labu']/parent::*</value>
      <webElementGuid>47112bed-0ebc-4e15-b1ff-f7b0cd570087</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[19]</value>
      <webElementGuid>8603bd37-5911-44a9-b386-c5a8e36cc971</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'react-select-14-option-18' and (text() = 'Labu' or . = 'Labu')]</value>
      <webElementGuid>1b305e8a-9ffe-4674-83cd-c99647098b55</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
