<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Postcode_propPostcode</name>
   <tag></tag>
   <elementGuidId>a3ebfc3c-0a2e-4d8c-b9c6-5ecd15ecac54</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='propPostcode']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#propPostcode</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e8824859-1915-4dfa-851a-e4a572b6c091</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>29ef21fe-9134-43f6-a908-9bdee805a2d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>propPostcode</value>
      <webElementGuid>661e5118-d01d-4bd0-907e-65465b3862fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>propPostcode</value>
      <webElementGuid>e6e65323-2392-422c-b162-3c653f4c3010</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Postcode</value>
      <webElementGuid>713a1e8c-9c37-486a-bf66-6100a1d8b58a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control propmaster-input-trans propmaster-input-value</value>
      <webElementGuid>a8f1e553-d9fb-4c08-9218-50d4a0fd8d97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;propPostcode&quot;)</value>
      <webElementGuid>4b595b50-566b-4daf-87f7-bc0c591ede65</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='propPostcode']</value>
      <webElementGuid>0a4f2ca1-933b-43d6-9b82-4ea274c730f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kt_app_content_container']/div/div/div[2]/div/div[3]/div/div/div/form[2]/div/div[3]/div[2]/div/div/input</value>
      <webElementGuid>9588e796-83da-4d30-8e06-ef3c98b657ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/input</value>
      <webElementGuid>9c06063d-37bb-4a1a-9dbf-b25daacf20de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'propPostcode' and @id = 'propPostcode' and @placeholder = 'Postcode']</value>
      <webElementGuid>2ed9e722-de18-4fe0-ad42-4527ec706fd6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
