<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_City_propCity</name>
   <tag></tag>
   <elementGuidId>209ea1bf-0ac6-49c7-ba6a-93d77df4d84a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='propCity']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#propCity</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>27186bf9-e547-4d35-95ed-dd83098118c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f6ce4522-3fb1-4e45-8a2a-12873536851f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>propCity</value>
      <webElementGuid>55469899-2d59-4b2e-8c8d-b23c1967c19e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>propCity</value>
      <webElementGuid>5097a64e-04a9-4245-9ce3-07199bdeea0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>City</value>
      <webElementGuid>04aba05c-a5de-48fc-9c8b-9a060581c80b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control propmaster-input-trans propmaster-input-value</value>
      <webElementGuid>c1b30ec2-7528-4cef-adc0-9072efb7369b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;propCity&quot;)</value>
      <webElementGuid>e956a177-276f-498b-9ecc-23b1a36fda92</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='propCity']</value>
      <webElementGuid>e2f2542c-da96-418e-bb1d-45df4eb51309</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kt_app_content_container']/div/div/div[2]/div/div[3]/div/div/div/form[2]/div/div[3]/div/div/div/input</value>
      <webElementGuid>1dbdf1ab-a5ff-4ce8-86bb-4248709e1d8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/input</value>
      <webElementGuid>f6c91552-09fc-47d4-85c3-4849669d0f4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'propCity' and @id = 'propCity' and @placeholder = 'City']</value>
      <webElementGuid>b2e91117-4b7d-4d1b-87b2-0eaa97e437d3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
