<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Property Name_propName</name>
   <tag></tag>
   <elementGuidId>3e7c38c3-23a7-446c-bcc1-6207d51dcc04</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='propName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#propName</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ce6aded6-9725-4aea-ade8-b8ffd1569db1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3cf11965-b9c6-4247-a0d2-f6a78b308ec2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>propName</value>
      <webElementGuid>c7083778-0a87-4efc-87cd-ca358da76551</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>propName</value>
      <webElementGuid>8ef96356-d6bd-45c6-a3a7-055e0d2dc230</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Property Name</value>
      <webElementGuid>c01d58c4-1b41-49b5-a4dd-983422534063</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control propmaster-input-trans propmaster-input-value</value>
      <webElementGuid>765ea4f3-6e83-4802-bc86-6fdf94c51d12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>T</value>
      <webElementGuid>eb6f5e99-fef5-4366-bc6c-0856280e9601</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;propName&quot;)</value>
      <webElementGuid>6716da00-ec2b-47e2-9cec-ad7d41fd651e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='propName']</value>
      <webElementGuid>a857b638-8c08-422c-8c8f-dcba0ff1d64f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kt_app_content_container']/div/div/div[2]/div/div[3]/div[2]/div/div/form/div/div/div/input</value>
      <webElementGuid>a25de53c-fdc6-4fe3-8204-82e0c82eb93c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>60508024-0583-4096-a59a-48b4736e1256</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'propName' and @id = 'propName' and @placeholder = 'Property Name']</value>
      <webElementGuid>9fce66f8-cb6d-4a8e-b73d-31249c47ed8f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
