<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Address Line 1_propAddressLine1</name>
   <tag></tag>
   <elementGuidId>10bdd1f8-fadb-432a-8bf2-bfc2e9996bcd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='propAddressLine1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#propAddressLine1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6bfe984b-533c-408d-8029-d74f2ebc6f0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>31137b24-4315-4449-8b30-bc7e299361ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>propAddressLine1</value>
      <webElementGuid>132815f3-a1a7-437b-85de-05a3c8cb1725</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>propAddressLine1</value>
      <webElementGuid>f2ea45b1-96bc-4ebd-992b-bbed3149b2aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Address Line 1</value>
      <webElementGuid>90a774f9-4c89-43be-83e6-673a45e31348</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control propmaster-input-trans propmaster-input-value</value>
      <webElementGuid>bff7d691-aed3-46b4-8e9b-1ca46b076321</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;propAddressLine1&quot;)</value>
      <webElementGuid>a19ce219-171e-4f3d-9bf0-d5dd5bcc1cc7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='propAddressLine1']</value>
      <webElementGuid>cb0fed8f-fb15-4e92-b17a-b42d1d1562d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kt_app_content_container']/div/div/div[2]/div/div[3]/div/div/div/form[2]/div/div/div/input</value>
      <webElementGuid>1dce6c93-c7dc-4063-8a6a-2c7d3eb07302</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form[2]/div/div/div/input</value>
      <webElementGuid>a2b4a020-2441-4fa6-827b-8a48f3b1ba5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'propAddressLine1' and @id = 'propAddressLine1' and @placeholder = 'Address Line 1']</value>
      <webElementGuid>b15c5b3f-2753-481f-90ef-50827a0cb351</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
