<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Pending</name>
   <tag></tag>
   <elementGuidId>972f89d0-333b-4b86-8f33-6f4b5a9bba4d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='kt_app_content_container']/div/div/div[2]/div[2]/div/div/div/table/tbody/tr/td[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td:nth-of-type(4)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>d67ae96b-0676-46ca-be2b-3c6340bd63e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pending</value>
      <webElementGuid>13bfdcee-b4a9-417e-9a7e-84abe3a7f877</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_app_content_container&quot;)/div[@class=&quot;page-wrapper&quot;]/div[@class=&quot;page-statistic-wrapper&quot;]/div[@class=&quot;page-content-wrapper&quot;]/div[2]/div[@class=&quot;master-table-wrapper&quot;]/div[@class=&quot;infinite-scroll-component__outerdiv&quot;]/div[@class=&quot;infinite-scroll-component&quot;]/table[@class=&quot;db-pd-table-content table gs-4&quot;]/tbody[1]/tr[1]/td[4]</value>
      <webElementGuid>27ab9275-a1d9-4df6-9f65-4d77fde99f8d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kt_app_content_container']/div/div/div[2]/div[2]/div/div/div/table/tbody/tr/td[4]</value>
      <webElementGuid>61e5f57d-ef07-4a2e-9a8e-66ec785c132a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jalan Tiara Sendayan 2, Taman Tiara Sendayan Labu 71900 Negeri Sembilan Malaysia'])[1]/following::td[2]</value>
      <webElementGuid>66a1a604-f80b-4a9c-91cc-31e5f63d0beb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='The Apartment 2'])[1]/following::td[3]</value>
      <webElementGuid>1b1c78a9-9043-433d-901d-656ad561cbe8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Looks like you', &quot;'&quot;, 've reached the end')])[1]/preceding::td[1]</value>
      <webElementGuid>65488c0b-f5db-4a89-b057-54ca80fd838f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]</value>
      <webElementGuid>da5d05e8-1593-4198-95e2-7fd925c5d2a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Pending' or . = 'Pending')]</value>
      <webElementGuid>9cf4443e-4344-4150-9a7d-04e52952d40a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
