<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_User Name  Email Address</name>
   <tag></tag>
   <elementGuidId>bc4174f5-ae0f-4a0c-9a1c-1aa4a4b89be8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='kt_login_signin_form']/div[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.auth-input-box</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f3489ce1-5052-444d-8fb0-4af3527052b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>auth-input-box</value>
      <webElementGuid>e793df3c-7581-4a3b-b2e6-286b6d51f269</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>User Name / Email Address</value>
      <webElementGuid>c0df08a5-8251-47f1-bc7f-3c00cb811fdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_login_signin_form&quot;)/div[@class=&quot;fv-row mb-8&quot;]/div[@class=&quot;auth-input-box&quot;]</value>
      <webElementGuid>9608d450-11d3-4882-acac-6a1f17893c9a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='kt_login_signin_form']/div[2]/div</value>
      <webElementGuid>25ecf2e9-8544-481a-a847-55168c80088e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/preceding::div[1]</value>
      <webElementGuid>3c3c110a-44d9-4529-a086-286f95968d8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div</value>
      <webElementGuid>02bb8d5b-a18e-45dc-b89e-f083c543fcd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'User Name / Email Address' or . = 'User Name / Email Address')]</value>
      <webElementGuid>f21659a7-405d-4e18-8d61-fc098522678f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
