<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_dashboard</name>
   <tag></tag>
   <elementGuidId>85c51808-b2a0-4485-891c-491376fe6f10</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='navItem-dashboard-0']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#navItem-dashboard-0 > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c54d8e0e-dc77-419d-9144-1120707e2a16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>dashboard</value>
      <webElementGuid>bd2cb322-00b2-4a5e-8144-a46be6e90949</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navItem-dashboard-0&quot;)/span[1]</value>
      <webElementGuid>aa422e88-ae75-4fbe-8192-c38845dcc88d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='navItem-dashboard-0']/span</value>
      <webElementGuid>47ffc885-9789-4bb7-8a47-7b21f3b18d28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nextsix.Agent'])[1]/following::span[1]</value>
      <webElementGuid>32fdded5-a85f-4bbf-a4ce-b76e3a6fce84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='my guidance'])[1]/preceding::span[1]</value>
      <webElementGuid>2366bfd0-cc42-4007-9d28-bb65309c3e96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='my profile'])[1]/preceding::span[2]</value>
      <webElementGuid>859b7b60-d59e-4e6e-968d-e2d2ab649ba8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='dashboard']/parent::*</value>
      <webElementGuid>1b0565c2-3d6a-4633-9908-a1a1f0adb912</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a/span</value>
      <webElementGuid>a712d273-2370-4bc6-b824-25d6d88fc564</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'dashboard' or . = 'dashboard')]</value>
      <webElementGuid>1f2ea5d1-8c3b-4322-a7f2-53d6fd7b8a62</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
